version: "3.9"
services:
  bootcamp_express_server:
    build:
      context: .
    environment:
      PORT: 9000
      DATABASE_URL: file:./dev.db
    command: "./run.sh"
    ports:
      - "9000:9000"
    volumes:
      - .:/code
      - /code/node_modules
